### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by tkosamja** [RaitaroH/WhatsApp-DeepDark#3]
Not really a problem and I'm not even sure you can fix this but this is what emojis look like:

![capture](https://user-images.githubusercontent.com/26143003/36907423-8c3595fc-1e30-11e8-8df1-ac61755e700e.PNG)

**Comment by vednoc** [comment]
I went a little bit in-depth about it [here](https://forum.userstyles.org/discussion/64020). Another person asked about it [here](https://forum.userstyles.org/discussion/64417). The question right now is if someone is kind enough to provide a new background image for each and every emoji set.

Also, you can use : in the input area followed by emoji name and you'll get a small popup menu to choose from emojis matching that name. The issue is also present there, but it's all around a faster way to send emojis. Here's an example, paste this in the input area and just press tab/enter to confirm the emoji, arrows to move around:
```
:smile
```

**Comment by tkosamja** [comment]
Yeah, just as I thought. Once again Whatsapp devs prove their incompetence. Impossible to fix, but let's wait to see what @RaitaroH has to say.
Also, thanks for the replies and tips @vednoc!

**Comment by vednoc** [comment]
I don't necessarily agree with the way they do things, especially with the changes in the last few months that obfuscated almost the entirety of their code, but it could be way worse. I've been really hoping for them to use transparent background for the latest iteration of iOS emojis, but sadly that wasn't the case.

You're welcome. If there's anything else, I would be happy to help.

**Comment by RaitaroH** [comment]
@vednoc @tkosamja I simply tried to make the face emojis look ok by adding a border radius. I cannot try to remove the background without spending way too much time rendering everything by hand or trying to do a messy job with tools. The image is small thus the render will end up badly. Also they add new emojis all the time thus it is a futile effort.

**Comment by tkosamja** [comment]
Yeah I understand, it's ridiculous.
